### ISSUE TITLE
Pascal-Part configs and datasets

### ISSUE THREAD

**Issue by xjwu1024** [TACJu/Compositor#5]
Hi,

Would it be possible to release the Pascal Part configs and datasets as well?

Thanks

**Comment by TACJu** [comment]
Hi,

Thanks for your interest in our work. We just uploaded the Pascal-Part dataset we used in this work: https://drive.google.com/file/d/162IWo6BmPXJek5Wfw-JautqKHZLBcgNY/view?usp=sharing. We will update the configs soon.

Best
