### ISSUE TITLE
Pascal Part datasets

### ISSUE THREAD

**Issue by gxjlhx** [TACJu/Compositor#6]
Hi,

Would it be possible to release the Pascal Part datasets as well?

Thanks

**Comment by TACJu** [comment]
Hi,

Thanks for your interest in our work. We just uploaded the Pascal-Part dataset we used in this work: https://drive.google.com/file/d/162IWo6BmPXJek5Wfw-JautqKHZLBcgNY/view?usp=sharing.

Best
